SRCS := ccl/ccl_get.cpp \
	ccl/ccl_release.cpp \
	ccl/ccl_iterate.cpp \
	ccl/ccl_parse.cpp \
	ccl/ccl_reset.cpp \
	sense/wavesense.cpp

TARGET = $(XS_LIB)/libxs.a
include $(XS_SCRIPTS)/compile_lib.mk
